-- AUTO-GENERATED from Blizzard client realm list (LibRealmInfo unpack format).
-- Regenerate: python Tools/gen_realm_catalog.py
local _, ns = ...
ns.RealmCatalogData = {
	["Aegwynn"] = { locale = "enUS", region = "US", tz = "CST" },
	["Aerie Peak"] = { locale = "enUS", region = "US", tz = "PST" },
	["Agamaggan"] = { locale = "enUS", region = "US", tz = "CST" },
	["Aggramar"] = { locale = "enUS", region = "US", tz = "CST" },
	["Akama"] = { locale = "enUS", region = "US", tz = "PST" },
	["Alexstrasza"] = { locale = "enUS", region = "US", tz = "CST" },
	["Alleria"] = { locale = "enUS", region = "US", tz = "CST" },
	["Altar of Storms"] = { locale = "enUS", region = "US", tz = "EST" },
	["Alterac Mountains"] = { locale = "enUS", region = "US", tz = "EST" },
	["Aman'Thul"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Andorhal"] = { locale = "enUS", region = "US", tz = "PST" },
	["Anetheron"] = { locale = "enUS", region = "US", tz = "EST" },
	["Antonidas"] = { locale = "enUS", region = "US", tz = "PST" },
	["Anub'arak"] = { locale = "enUS", region = "US", tz = "CST" },
	["Anvilmar"] = { locale = "enUS", region = "US", tz = "CST" },
	["Arathor"] = { locale = "enUS", region = "US", tz = "PST" },
	["Archimonde"] = { locale = "enUS", region = "US", tz = "CST" },
	["Area 52"] = { locale = "enUS", region = "US", tz = "EST" },
	["Argent Dawn"] = { locale = "enUS", region = "US", tz = "EST" },
	["Arthas"] = { locale = "enUS", region = "US", tz = "EST" },
	["Arygos"] = { locale = "enUS", region = "US", tz = "EST" },
	["Auchindoun"] = { locale = "enUS", region = "US", tz = "CST" },
	["Azgalor"] = { locale = "enUS", region = "US", tz = "CST" },
	["Azjol-Nerub"] = { locale = "enUS", region = "US", tz = "MST" },
	["Azralon"] = { locale = "ptBR", region = "US", tz = "undefined" },
	["Azshara"] = { locale = "enUS", region = "US", tz = "CST" },
	["Azuremyst"] = { locale = "enUS", region = "US", tz = "CST" },
	["Baelgun"] = { locale = "enUS", region = "US", tz = "PST" },
	["Balnazzar"] = { locale = "enUS", region = "US", tz = "EST" },
	["Barthilas"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Black Dragonflight"] = { locale = "enUS", region = "US", tz = "EST" },
	["Blackhand"] = { locale = "enUS", region = "US", tz = "CST" },
	["Blackrock"] = { locale = "enUS", region = "US", tz = "PST" },
	["Blackwater Raiders"] = { locale = "enUS", region = "US", tz = "MST" },
	["Blackwing Lair"] = { locale = "enUS", region = "US", tz = "CST" },
	["Blade's Edge"] = { locale = "enUS", region = "US", tz = "CST" },
	["Bladefist"] = { locale = "enUS", region = "US", tz = "CST" },
	["Bleeding Hollow"] = { locale = "enUS", region = "US", tz = "EST" },
	["Blood Furnace"] = { locale = "enUS", region = "US", tz = "EST" },
	["Bloodhoof"] = { locale = "enUS", region = "US", tz = "EST" },
	["Bloodscalp"] = { locale = "enUS", region = "US", tz = "MST" },
	["Bonechewer"] = { locale = "enUS", region = "US", tz = "CST" },
	["Borean Tundra"] = { locale = "enUS", region = "US", tz = "PST" },
	["Boulderfist"] = { locale = "enUS", region = "US", tz = "MST" },
	["Bronzebeard"] = { locale = "enUS", region = "US", tz = "PST" },
	["Burning Blade"] = { locale = "enUS", region = "US", tz = "EST" },
	["Burning Legion"] = { locale = "enUS", region = "US", tz = "CST" },
	["Caelestrasz"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Cairne"] = { locale = "enUS", region = "US", tz = "MST" },
	["Cenarion Circle"] = { locale = "enUS", region = "US", tz = "PST" },
	["Cenarius"] = { locale = "enUS", region = "US", tz = "PST" },
	["Cho'gall"] = { locale = "enUS", region = "US", tz = "CST" },
	["Cho’gall"] = { locale = "frFR", region = "EU", tz = "Cho'gall" },
	["Chromaggus"] = { locale = "enUS", region = "US", tz = "CST" },
	["Coilfang"] = { locale = "enUS", region = "US", tz = "PST" },
	["Crushridge"] = { locale = "enUS", region = "US", tz = "CST" },
	["Daggerspine"] = { locale = "enUS", region = "US", tz = "CST" },
	["Dalaran"] = { locale = "enUS", region = "US", tz = "EST" },
	["Dalvengyr"] = { locale = "enUS", region = "US", tz = "PST" },
	["Dark Iron"] = { locale = "enUS", region = "US", tz = "PST" },
	["Darkspear"] = { locale = "enUS", region = "US", tz = "MST" },
	["Darrowmere"] = { locale = "enUS", region = "US", tz = "PST" },
	["Dath'Remar"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Dawnbringer"] = { locale = "enUS", region = "US", tz = "CST" },
	["Deathwing"] = { locale = "enUS", region = "US", tz = "PST" },
	["Demon Soul"] = { locale = "enUS", region = "US", tz = "PST" },
	["Dentarg"] = { locale = "enUS", region = "US", tz = "CST" },
	["Destromath"] = { locale = "enUS", region = "US", tz = "CST" },
	["Dethecus"] = { locale = "enUS", region = "US", tz = "CST" },
	["Detheroc"] = { locale = "enUS", region = "US", tz = "CST" },
	["Doomhammer"] = { locale = "enUS", region = "US", tz = "PST" },
	["Draenor"] = { locale = "enUS", region = "US", tz = "PST" },
	["Dragonblight"] = { locale = "enUS", region = "US", tz = "PST" },
	["Dragonmaw"] = { locale = "enUS", region = "US", tz = "PST" },
	["Drak'Tharon"] = { locale = "enUS", region = "US", tz = "EST" },
	["Drak'thul"] = { locale = "enUS", region = "US", tz = "PST" },
	["Draka"] = { locale = "enUS", region = "US", tz = "PST" },
	["Drakkari"] = { locale = "esMX", region = "US", tz = "CST" },
	["Dreadmaul"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Drenden"] = { locale = "enUS", region = "US", tz = "PST" },
	["Dunemaul"] = { locale = "enUS", region = "US", tz = "MST" },
	["Durotan"] = { locale = "enUS", region = "US", tz = "EST" },
	["Duskwood"] = { locale = "enUS", region = "US", tz = "EST" },
	["Earthen Ring"] = { locale = "enUS", region = "US", tz = "EST" },
	["Echo Isles"] = { locale = "enUS", region = "US", tz = "PST" },
	["Eitrigg"] = { locale = "enUS", region = "US", tz = "CST" },
	["Eldre'Thalas"] = { locale = "enUS", region = "US", tz = "EST" },
	["Elune"] = { locale = "enUS", region = "US", tz = "EST" },
	["Emerald Dream"] = { locale = "enUS", region = "US", tz = "CST" },
	["Eonar"] = { locale = "enUS", region = "US", tz = "EST" },
	["Eredar"] = { locale = "enUS", region = "US", tz = "CST" },
	["Executus"] = { locale = "enUS", region = "US", tz = "PST" },
	["Exodar"] = { locale = "enUS", region = "US", tz = "EST" },
	["Farstriders"] = { locale = "enUS", region = "US", tz = "PST" },
	["Feathermoon"] = { locale = "enUS", region = "US", tz = "PST" },
	["Fenris"] = { locale = "enUS", region = "US", tz = "PST" },
	["Firetree"] = { locale = "enUS", region = "US", tz = "EST" },
	["Fizzcrank"] = { locale = "enUS", region = "US", tz = "CST" },
	["Frostmane"] = { locale = "enUS", region = "US", tz = "CST" },
	["Frostmourne"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Frostwolf"] = { locale = "enUS", region = "US", tz = "PST" },
	["Galakrond"] = { locale = "enUS", region = "US", tz = "CST" },
	["Gallywix"] = { locale = "ptBR", region = "US", tz = "undefined" },
	["Garithos"] = { locale = "enUS", region = "US", tz = "CST" },
	["Garona"] = { locale = "enUS", region = "US", tz = "CST" },
	["Garrosh"] = { locale = "enUS", region = "US", tz = "EST" },
	["Ghostlands"] = { locale = "enUS", region = "US", tz = "CST" },
	["Gilneas"] = { locale = "enUS", region = "US", tz = "EST" },
	["Gnomeregan"] = { locale = "enUS", region = "US", tz = "PST" },
	["Goldrinn"] = { locale = "ptBR", region = "US", tz = "undefined" },
	["Gorefiend"] = { locale = "enUS", region = "US", tz = "CST" },
	["Gorgonnash"] = { locale = "enUS", region = "US", tz = "EST" },
	["Greymane"] = { locale = "enUS", region = "US", tz = "CST" },
	["Grizzly Hills"] = { locale = "enUS", region = "US", tz = "EST" },
	["Gul'dan"] = { locale = "enUS", region = "US", tz = "EST" },
	["Gundrak"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Gurubashi"] = { locale = "enUS", region = "US", tz = "CST" },
	["Hakkar"] = { locale = "enUS", region = "US", tz = "CST" },
	["Haomarush"] = { locale = "enUS", region = "US", tz = "CST" },
	["Hellscream"] = { locale = "enUS", region = "US", tz = "CST" },
	["Hydraxis"] = { locale = "enUS", region = "US", tz = "MST" },
	["Hyjal"] = { locale = "enUS", region = "US", tz = "PST" },
	["Icecrown"] = { locale = "enUS", region = "US", tz = "CST" },
	["Illidan"] = { locale = "enUS", region = "US", tz = "CST" },
	["Jaedenar"] = { locale = "enUS", region = "US", tz = "CST" },
	["Jubei'Thos"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Kael'thas"] = { locale = "enUS", region = "US", tz = "CST" },
	["Kalecgos"] = { locale = "enUS", region = "US", tz = "PST" },
	["Kargath"] = { locale = "enUS", region = "US", tz = "EST" },
	["Kel'Thuzad"] = { locale = "enUS", region = "US", tz = "MST" },
	["Khadgar"] = { locale = "enUS", region = "US", tz = "CST" },
	["Khaz Modan"] = { locale = "enUS", region = "US", tz = "MST" },
	["Khaz'goroth"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Kil'jaeden"] = { locale = "enUS", region = "US", tz = "PST" },
	["Kilrogg"] = { locale = "enUS", region = "US", tz = "PST" },
	["Kirin Tor"] = { locale = "enUS", region = "US", tz = "CST" },
	["Korgath"] = { locale = "enUS", region = "US", tz = "CST" },
	["Korialstrasz"] = { locale = "enUS", region = "US", tz = "EST" },
	["Kul Tiras"] = { locale = "enUS", region = "US", tz = "CST" },
	["Laughing Skull"] = { locale = "enUS", region = "US", tz = "CST" },
	["Lethon"] = { locale = "enUS", region = "US", tz = "CST" },
	["Lightbringer"] = { locale = "enUS", region = "US", tz = "PST" },
	["Lightning's Blade"] = { locale = "enUS", region = "US", tz = "EST" },
	["Lightninghoof"] = { locale = "enUS", region = "US", tz = "CST" },
	["Llane"] = { locale = "enUS", region = "US", tz = "EST" },
	["Lothar"] = { locale = "enUS", region = "US", tz = "EST" },
	["Madoran"] = { locale = "enUS", region = "US", tz = "CST" },
	["Maelstrom"] = { locale = "enUS", region = "US", tz = "CST" },
	["Magtheridon"] = { locale = "enUS", region = "US", tz = "EST" },
	["Maiev"] = { locale = "enUS", region = "US", tz = "MST" },
	["Mal'Ganis"] = { locale = "enUS", region = "US", tz = "CST" },
	["Malfurion"] = { locale = "enUS", region = "US", tz = "EST" },
	["Malorne"] = { locale = "enUS", region = "US", tz = "EST" },
	["Malygos"] = { locale = "enUS", region = "US", tz = "CST" },
	["Mannoroth"] = { locale = "enUS", region = "US", tz = "EST" },
	["Medivh"] = { locale = "enUS", region = "US", tz = "EST" },
	["Misha"] = { locale = "enUS", region = "US", tz = "CST" },
	["Mok'Nathal"] = { locale = "enUS", region = "US", tz = "PST" },
	["Moon Guard"] = { locale = "enUS", region = "US", tz = "CST" },
	["Moonrunner"] = { locale = "enUS", region = "US", tz = "PST" },
	["Mug'thol"] = { locale = "enUS", region = "US", tz = "PST" },
	["Muradin"] = { locale = "enUS", region = "US", tz = "CST" },
	["Nagrand"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Nathrezim"] = { locale = "enUS", region = "US", tz = "CST" },
	["Nazgrel"] = { locale = "enUS", region = "US", tz = "CST" },
	["Nazjatar"] = { locale = "enUS", region = "US", tz = "EST" },
	["Nemesis"] = { locale = "ptBR", region = "US", tz = "undefined" },
	["Ner'zhul"] = { locale = "enUS", region = "US", tz = "CST" },
	["Ner’zhul"] = { locale = "frFR", region = "EU", tz = "Ner'zhul" },
	["Nesingwary"] = { locale = "enUS", region = "US", tz = "CST" },
	["Nordrassil"] = { locale = "enUS", region = "US", tz = "CST" },
	["Norgannon"] = { locale = "enUS", region = "US", tz = "EST" },
	["Onyxia"] = { locale = "enUS", region = "US", tz = "EST" },
	["Perenolde"] = { locale = "enUS", region = "US", tz = "MST" },
	["Proudmoore"] = { locale = "enUS", region = "US", tz = "PST" },
	["Quel'dorei"] = { locale = "enUS", region = "US", tz = "CST" },
	["Quel'Thalas"] = { locale = "esMX", region = "US", tz = "CST" },
	["Ragnaros"] = { locale = "esMX", region = "US", tz = "CST" },
	["Ravencrest"] = { locale = "enUS", region = "US", tz = "CST" },
	["Ravenholdt"] = { locale = "enUS", region = "US", tz = "CST" },
	["Rexxar"] = { locale = "enUS", region = "US", tz = "CST" },
	["Rivendare"] = { locale = "enUS", region = "US", tz = "EST" },
	["Runetotem"] = { locale = "enUS", region = "US", tz = "CST" },
	["Sargeras"] = { locale = "enUS", region = "US", tz = "CST" },
	["Saurfang"] = { locale = "enUS", region = "US", tz = "AEST" },
	["Scarlet Crusade"] = { locale = "enUS", region = "US", tz = "PST" },
	["Scilla"] = { locale = "enUS", region = "US", tz = "PST" },
	["Sen'jin"] = { locale = "enUS", region = "US", tz = "CST" },
	["Sentinels"] = { locale = "enUS", region = "US", tz = "CST" },
	["Shadow Council"] = { locale = "enUS", region = "US", tz = "MST" },
	["Shadowmoon"] = { locale = "enUS", region = "US", tz = "CST" },
	["Shadowsong"] = { locale = "enUS", region = "US", tz = "PST" },
	["Shandris"] = { locale = "enUS", region = "US", tz = "PST" },
	["Shattered Halls"] = { locale = "enUS", region = "US", tz = "PST" },
	["Shattered Hand"] = { locale = "enUS", region = "US", tz = "PST" },
	["Shu'halo"] = { locale = "enUS", region = "US", tz = "CST" },
	["Silver Hand"] = { locale = "enUS", region = "US", tz = "PST" },
	["Silvermoon"] = { locale = "enUS", region = "US", tz = "PST" },
	["Sisters of Elune"] = { locale = "enUS", region = "US", tz = "PST" },
	["Skullcrusher"] = { locale = "enUS", region = "US", tz = "EST" },
	["Skywall"] = { locale = "enUS", region = "US", tz = "PST" },
	["Smolderthorn"] = { locale = "enUS", region = "US", tz = "CST" },
	["Spinebreaker"] = { locale = "enUS", region = "US", tz = "CST" },
	["Spirestone"] = { locale = "enUS", region = "US", tz = "EST" },
	["Staghelm"] = { locale = "enUS", region = "US", tz = "CST" },
	["Steamwheedle Cartel"] = { locale = "enUS", region = "US", tz = "CST" },
	["Stonemaul"] = { locale = "enUS", region = "US", tz = "MST" },
	["Stormrage"] = { locale = "enUS", region = "US", tz = "EST" },
	["Stormreaver"] = { locale = "enUS", region = "US", tz = "CST" },
	["Stormscale"] = { locale = "enUS", region = "US", tz = "EST" },
	["Suramar"] = { locale = "enUS", region = "US", tz = "PST" },
	["Tanaris"] = { locale = "enUS", region = "US", tz = "CST" },
	["Terenas"] = { locale = "enUS", region = "US", tz = "MST" },
	["Terokkar"] = { locale = "enUS", region = "US", tz = "CST" },
	["Thaurissan"] = { locale = "enUS", region = "US", tz = "AEST" },
	["The Forgotten Coast"] = { locale = "enUS", region = "US", tz = "EST" },
	["The Scryers"] = { locale = "enUS", region = "US", tz = "EST" },
	["The Underbog"] = { locale = "enUS", region = "US", tz = "CST" },
	["The Venture Co"] = { locale = "enUS", region = "US", tz = "CST" },
	["Thorium Brotherhood"] = { locale = "enUS", region = "US", tz = "PST" },
	["Thrall"] = { locale = "enUS", region = "US", tz = "EST" },
	["Thunderhorn"] = { locale = "enUS", region = "US", tz = "CST" },
	["Thunderlord"] = { locale = "enUS", region = "US", tz = "CST" },
	["Tichondrius"] = { locale = "enUS", region = "US", tz = "PST" },
	["Tol Barad"] = { locale = "ptBR", region = "US", tz = "undefined" },
	["Tortheldrin"] = { locale = "enUS", region = "US", tz = "CST" },
	["Trollbane"] = { locale = "enUS", region = "US", tz = "EST" },
	["Turalyon"] = { locale = "enUS", region = "US", tz = "EST" },
	["Twisting Nether"] = { locale = "enUS", region = "US", tz = "CST" },
	["Uldaman"] = { locale = "enUS", region = "US", tz = "CST" },
	["Uldum"] = { locale = "enUS", region = "US", tz = "PST" },
	["Undermine"] = { locale = "enUS", region = "US", tz = "CST" },
	["Ursin"] = { locale = "enUS", region = "US", tz = "PST" },
	["Uther"] = { locale = "enUS", region = "US", tz = "CST" },
	["Vashj"] = { locale = "enUS", region = "US", tz = "PST" },
	["Vek'nilash"] = { locale = "enUS", region = "US", tz = "CST" },
	["Velen"] = { locale = "enUS", region = "US", tz = "EST" },
	["Warsong"] = { locale = "enUS", region = "US", tz = "EST" },
	["Whisperwind"] = { locale = "enUS", region = "US", tz = "CST" },
	["Wildhammer"] = { locale = "enUS", region = "US", tz = "CST" },
	["Windrunner"] = { locale = "enUS", region = "US", tz = "PST" },
	["Winterhoof"] = { locale = "enUS", region = "US", tz = "PST" },
	["Wyrmrest Accord"] = { locale = "enUS", region = "US", tz = "PST" },
	["Ysera"] = { locale = "enUS", region = "US", tz = "EST" },
	["Ysondre"] = { locale = "enUS", region = "US", tz = "EST" },
	["Zangarmarsh"] = { locale = "enUS", region = "US", tz = "CST" },
	["Zul'jin"] = { locale = "enUS", region = "US", tz = "EST" },
	["Zuluhed"] = { locale = "enUS", region = "US", tz = "PST" },
	["Азурегос"] = { locale = "ruRU", region = "EU", tz = "Azuregos" },
	["Борейская тундра"] = { locale = "ruRU", region = "EU", tz = "Borean Tundra" },
	["Вечная Песня"] = { locale = "ruRU", region = "EU", tz = "Eversong" },
	["Галакронд"] = { locale = "ruRU", region = "EU", tz = "Galakrond" },
	["Голдринн"] = { locale = "ruRU", region = "EU", tz = "Goldrinn" },
	["Гордунни"] = { locale = "ruRU", region = "EU", tz = "Gordunni" },
	["Гром"] = { locale = "ruRU", region = "EU", tz = "Grom" },
	["Дракономор"] = { locale = "ruRU", region = "EU", tz = "Fordragon" },
	["Король-лич"] = { locale = "ruRU", region = "EU", tz = "Lich King" },
	["Пиратская Бухта"] = { locale = "ruRU", region = "EU", tz = "Booty Bay" },
	["Подземье"] = { locale = "ruRU", region = "EU", tz = "Deepholm" },
	["Разувий"] = { locale = "ruRU", region = "EU", tz = "Razuvious" },
	["Ревущий фьорд"] = { locale = "ruRU", region = "EU", tz = "Howling Fjord" },
	["Свежеватель Душ"] = { locale = "ruRU", region = "EU", tz = "Soulflayer" },
	["Седогрив"] = { locale = "ruRU", region = "EU", tz = "Greymane" },
	["Страж Смерти"] = { locale = "ruRU", region = "EU", tz = "Deathguard" },
	["Термоштепсель"] = { locale = "ruRU", region = "EU", tz = "Thermaplugg" },
	["Ткач Смерти"] = { locale = "ruRU", region = "EU", tz = "Deathweaver" },
	["Черный Шрам"] = { locale = "ruRU", region = "EU", tz = "Blackscar" },
	["Ясеневый лес"] = { locale = "ruRU", region = "EU", tz = "Ashenvale" },
	["世界之樹"] = { locale = "zhTW", region = "TW", tz = "World Tree" },
	["亞雷戈斯"] = { locale = "zhTW", region = "TW", tz = "Arygos" },
	["冰霜之刺"] = { locale = "zhTW", region = "TW", tz = "Frostmane" },
	["冰風崗哨"] = { locale = "zhTW", region = "TW", tz = "Chillwind Point" },
	["地獄吼"] = { locale = "zhTW", region = "TW", tz = "Hellscream" },
	["夜空之歌"] = { locale = "zhTW", region = "TW", tz = "Nightsong" },
	["天空之牆"] = { locale = "zhTW", region = "TW", tz = "Skywall" },
	["寒冰皇冠"] = { locale = "zhTW", region = "TW", tz = "Icecrown" },
	["尖石"] = { locale = "zhTW", region = "TW", tz = "Spirestone" },
	["屠魔山谷"] = { locale = "zhTW", region = "TW", tz = "Demon Fall Canyon" },
	["巨龍之喉"] = { locale = "zhTW", region = "TW", tz = "Dragonmaw" },
	["憤怒使者"] = { locale = "zhTW", region = "TW", tz = "Wrathbringer" },
	["日落沼澤"] = { locale = "zhTW", region = "TW", tz = "Sundown Marsh" },
	["暗影之月"] = { locale = "zhTW", region = "TW", tz = "Shadowmoon" },
	["水晶之刺"] = { locale = "zhTW", region = "TW", tz = "Crystalpine Stinger" },
	["狂熱之刃"] = { locale = "zhTW", region = "TW", tz = "Zealot Blade" },
	["眾星之子"] = { locale = "zhTW", region = "TW", tz = "Quel'dorei" },
	["米奈希爾"] = { locale = "zhTW", region = "TW", tz = "Menethil" },
	["聖光之願"] = { locale = "zhTW", region = "TW", tz = "Light's Hope" },
	["血之谷"] = { locale = "zhTW", region = "TW", tz = "Bleeding Hollow" },
	["語風"] = { locale = "zhTW", region = "TW", tz = "Whisperwind" },
	["銀翼要塞"] = { locale = "zhTW", region = "TW", tz = "Silverwing Hold" },
	["阿薩斯"] = { locale = "zhTW", region = "TW", tz = "Arthas" },
	["雲蛟衛"] = { locale = "zhTW", region = "TW", tz = "Order of the Cloud Serpent" },
	["雷鱗"] = { locale = "zhTW", region = "TW", tz = "Stormscale" },
	["가로나"] = { locale = "koKR", region = "KR", tz = "Garona" },
	["굴단"] = { locale = "koKR", region = "KR", tz = "Gul'dan" },
	["노르간논"] = { locale = "koKR", region = "KR", tz = "Norgannon" },
	["달라란"] = { locale = "koKR", region = "KR", tz = "Dalaran" },
	["데스윙"] = { locale = "koKR", region = "KR", tz = "Deathwing" },
	["듀로탄"] = { locale = "koKR", region = "KR", tz = "Durotan" },
	["렉사르"] = { locale = "koKR", region = "KR", tz = "Rexxar" },
	["말퓨리온"] = { locale = "koKR", region = "KR", tz = "Malfurion" },
	["불타는 군단"] = { locale = "koKR", region = "KR", tz = "Burning Legion" },
	["세나리우스"] = { locale = "koKR", region = "KR", tz = "Cenarius" },
	["스톰레이지"] = { locale = "koKR", region = "KR", tz = "Stormrage" },
	["아즈샤라"] = { locale = "koKR", region = "KR", tz = "Azshara" },
	["알렉스트라자"] = { locale = "koKR", region = "KR", tz = "Alexstrasza" },
	["와일드해머"] = { locale = "koKR", region = "KR", tz = "Wildhammer" },
	["윈드러너"] = { locale = "koKR", region = "KR", tz = "Windrunner" },
	["줄진"] = { locale = "koKR", region = "KR", tz = "Zul'jin" },
	["하이잘"] = { locale = "koKR", region = "KR", tz = "Hyjal" },
	["헬스크림"] = { locale = "koKR", region = "KR", tz = "Hellscream" },
}
